name: Exécuter le script VCF

on:
  issues:  # Ce déclencheur réagit à la création d'une nouvelle issue
    types: [opened]  # Déclenchement lorsque l'issue est ouverte
  workflow_dispatch:  # Permet l'exécution manuelle via GitHub Actions
  push:  # Exécute le script à chaque fois qu'il y a un push
    branches:
      - main
  schedule:  # Exécute le workflow toutes les 3 heures
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Exécuter le script
      run: python script_vcf.py
